#!/bin/bash
set -e

USER=rminder
if ! id -u ${USER} > /dev/null 2>&1; then 
    echo "User ${USER} does not exist."
    exit 1
fi

APPLICATION_DIR="/var/lib/rminder-caddy"
mkdir -p "$APPLICATION_DIR"
chown $USER:nogroup -R "$APPLICATION_DIR"
chmod 600 -R "$APPLICATION_DIR"
chmod +x "$APPLICATION_DIR"

echo "Directory $APPLICATION_DIR created and permissions set."
